### ISSUE TITLE
请求支持新版stylish

### ISSUE THREAD

**Issue by lychichem** [ywzhaiqi/userChromeJS#15]
为了修复在userstyles安装页面无法更新已安装的样式的问题，@JasonBarnabe 发布了stylish2.0.0系列版本，在这里可以下载：https://forum.userstyles.org/discussion/44032/stylish-for-firefox-2-0-0b3 ，但是这个系列把stylish编辑器的路径改掉了，所以请求前辈针对这个变化兼容一下，如果可以的话不胜感激！

**Comment by Firef0x** [comment]
@lychichem ，您好！

我小改了一下 [stylish2.0_edit.uc.js](https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/PteScript/stylish2.0_edit.uc.js) ，合并了 ywzhaiqi 大神的修改，可以作为 [stylish0.5_edit.uc.js](https://github.com/ywzhaiqi/userChromeJS/blob/master/stylishEdit/stylish0.5_edit.uc.js) 的替代品。不过功能上肯定不如 `Stylish Editor Mod` 扩展强大。热切期盼大神能够完善发布 [Stylish Editor Mod 汉化版](https://github.com/lychichem/localized-addons/tree/master/stylishmod200)。 :pray: 

此致！ :bow:

**Comment by lychichem** [comment]
汉化是有的，但是由于扩展本身的问题，目前只能做到鼠标悬停显示中文提示，更进一步汉化可能要修改扩展代码。不完全汉化可在我的github页面找到

发自我的 Windows Phone
________________________________
发件人: Fernando Gilberto Pereira da Silva<mailto:notifications@github.com>
发送时间: ‎2015/‎1/‎22 15:17
收件人: ywzhaiqi/userChromeJS<mailto:userChromeJS@noreply.github.com>
抄送: lychichem<mailto:leichixian@outlook.com>
主题: Re: [userChromeJS] 请求支持新版stylish (#15)

@lychichem ，您好！

我小改了一下 [stylish2.0_edit.uc.js](https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/PteScript/stylish2.0_edit.uc.js) ，合并了 ywzhaiqi 大神的修改，可以作为 [stylish0.5_edit.uc.js](https://github.com/ywzhaiqi/userChromeJS/blob/master/stylishEdit/stylish0.5_edit.uc.js) 的替代品。不过功能上肯定不如 `Stylish Editor Mod` 扩展强大。热切期盼大神能够完善发布 [Stylish Editor Mod 汉化版](https://github.com/lychichem/localized-addons/tree/master/stylishmod200)。 :pray:

此致！ :bow:

---

**Comment by Firef0x** [comment]
@lychichem 主要是你在帖子 https://www.firefox.net.cn/read-50107 上说找原作者问一下之后，就没有下文了。然后你在 [stylish2.0_edit don't support rich text mode · Issue #27](https://github.com/alice0775/userChrome.js/issues/27) 发帖后也没有下文了。希望你不是弃坑了…… :confounded:

**Comment by lychichem** [comment]
因为我只会翻译不会改代码，所以代码层面上的事我弄不来，对于那个扩展，如果作者能提供所有字串，社区肯定会第一时间汉化完成的，但是现在版主都不想管这种字串不全的，我忙着做毕设手头事情也不少，只好暂时放下了

发自我的 Windows Phone
________________________________
发件人: Fernando Gilberto Pereira da Silva<mailto:notifications@github.com>
发送时间: ‎2015/‎1/‎22 22:43
收件人: ywzhaiqi/userChromeJS<mailto:userChromeJS@noreply.github.com>
抄送: lychichem<mailto:leichixian@outlook.com>
主题: Re: [userChromeJS] 请求支持新版stylish (#15)

@lychichem 主要是你在帖子 https://www.firefox.net.cn/read-50107 上说找原作者问一下之后，就没有下文了。然后你在 [stylish2.0_edit don't support rich text mode · Issue #27](https://github.com/alice0775/userChrome.js/issues/27) 发帖后也没有下文了。希望你不是弃坑了…… :confounded:

---

**Comment by Firef0x** [comment]
@lychichem ，您好！

感谢提醒！我想现在已经完成了 `Stylish` 升级到 2.0 后的增强脚本升级工作：

- 原来使用 [stylish0.5_edit.uc.js](https://github.com/ywzhaiqi/userChromeJS/blob/master/stylishEdit/stylish0.5_edit.uc.js) 的，可以升级到 [stylish2.0_edit.uc.js](https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/PteScript/stylish2.0_edit.uc.js) 

- 原来使用 [StylishCustom.uc.js](http://pan.baidu.com/share/link?uk=2467242534&shareid=3781338190#path=%2F%5BUC%E8%84%9A%E6%9C%AC%5DStylishCustom) 的，可以升级到 [StylishCustom2.uc.js](https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/SubScript/StylishCustom2_0.0.1.uc.js)

- 原来使用 [userChromeJS_Mix.xpi](https://github.com/ywzhaiqi/userChromeJS/blob/master/userChromeJS_Mix.xpi/userChromeJS_Mix.xpi) 的，为了适应新版本 `Stylish` 使用标签页编辑，需要修改为 [userChromeJS_Mix.xpi](https://github.com/Firef0x/UserChrome/blob/master/Addons/userChromeJS_Mix.xpi/userChromeJS_Mix.xpi)

此致！ :bow:
