### ISSUE TITLE
addmenu condition多个or怎么写？

### ISSUE THREAD

**Issue by monkey-sking** [ywzhaiqi/userChromeJS#16]
addmenu condition多个or怎么写？
||无效

**Comment by ywzhaiqi** [comment]
请详细看示例

>示例：菜单出现的条件，排除了链接、图片、输入框、选择等多个条件

    page({
        label: "snaplinks批量操作模式",
        condition: "nolink noimage noinput noselect",
        oncommand: "snapLinks.init();"
    });

**Comment by monkey-sking** [comment]
condition: 'select link ',
我这么写想的是选中或链接下出现效果，
实际是选中且链接的情况下出现效果
我应该怎么写？
非常抱歉浪费你宝贵的时间。

**Comment by ywzhaiqi** [comment]
上面说了，使用  noinput noimage 排除的方式， select 和 link 2个是冲突的，不能共存。
