### ISSUE TITLE
showCompleteURL.uc.js和DownloadEnhance.uc.js在OS X下无效

### ISSUE THREAD

**Issue by niclau** [ywzhaiqi/userChromeJS#17]
请问是否有解?
OS X 10.10.2
Firefox 31 esr

**Comment by ywzhaiqi** [comment]
注： 本人目前已主用 chrome，故停止更新，请换用同类扩展

**Comment by Firef0x** [comment]
@niclau ，您好！

不妨试试新的 `downloadPlus.uc.js` 脚本，由 **w13998686967** 整合。
见 https://github.com/Firef0x/UserChrome/blob/master/UserChromeJS/PteScript/downloadPlus.uc.js

此致！

**Comment by niclau** [comment]
@Firef0x 谢谢你的好意。但，可惜在OS X下仍然无效。
