### ISSUE TITLE
YoukuantiadsModY 脚本当中的更新播放器功能已经失效

### ISSUE THREAD

**Issue by enerai** [ywzhaiqi/userChromeJS#19]
YoukuantiadsModY 脚本当中的更新播放器功能已经失效了啊。。

原来的播放器存储地点已经迁移为
“https://bitbucket.org/kafan15536900/haoutil”

，希望能够对应的做些调整~谢谢！

**Comment by ywzhaiqi** [comment]
注： 本人目前已主用 chrome，故停止更新，请换用同类扩展

**Comment by enerai** [comment]
现在 Chrome 下面的去广告扩展用哪个呢？会不会 unblock youku 有些冲突呢（因为代理设置的问题）

**Comment by ywzhaiqi** [comment]
本人使用全局过滤软件，未使用扩展。

**Comment by enerai** [comment]
原来在用系统层面的软件啊。你用的是哪个，推荐一下喽。我等下也去试试看~

**Comment by ywzhaiqi** [comment]
阿呆喵

**Comment by enerai** [comment]
十分感谢，我去试试！
