### ISSUE TITLE
SaveUserChromeJS.uc.js 需要更新

### ISSUE THREAD

**Issue by alwaystest** [ywzhaiqi/userChromeJS#20]
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIWebBrowserPersist#saveURI%28%29
火狐36以上 saveURI() 函数增加了一个参数。
SaveUserChromeJS.uc.js 失效了。

**Comment by ywzhaiqi** [comment]
fixed
